---
git_url: "https://github.com/ASKBOT/askbot-devel"
gitdir: "/home/{{ askbot_user }}/askbot.git"
appdir: "/home/askbot/myaskbot"
askbot_user: askbot
askbot_group: "{{ askbot_user }}"
askbot_domain: example.org
virtenv: "/home/{{ app_user }}/virtenv"
askbot_base_dir: "{{ appdir }}"

# Name of this Askbot instance.
askbot_name: myaskbot

askbot_logs_dir: "{{ appdir }}"
askbot_conf_dir: "{{ appdir }}/conf"
askbot_uploads_dir: "{{ appdir }}/upfiles"

# Maximum allowed size of attachment that user can upload (in kilobytes).
# ASKBOT_MAX_UPLOAD_FILE_SIZE
askbot_max_upload_file_size: 1024

# Local time zone for this instance. Choices can be found here:
#   http://en.wikipedia.org/wiki/List_of_tz_zones_by_name.
# Django setting `TIME_ZONE`.
askbot_timezone: "{{ timezone | default('Europe/Moscow') }}"

# A string representing the language code. This should be in standard language
# ID format (see https://docs.djangoproject.com/en/1.7/topics/i18n/#term-language-code).
# Django setting `LANGUAGE_CODE`.
askbot_lang: en-us

#
# uWSGI
#

# Bind to the specified unix (socket file path), or TCP socket (address:port).
askbot_uwsgi_socket: '127.0.0.1:8090'

# Number of workers/processes to spawn.
askbot_uwsgi_processes: "{{ ansible_processor_count }}"

# Hash of additional uwsgi parameters.
askbot_uwsgi_params:
  chmod-socket: '777'

#
# Database
#
askbot_db_host: localhost
# The database backend to use.
# Django database argument `ENGINE`.
# :choices: postgresql_psycopg2, mysql, sqlite3, oracle
askbot_db_engine: mysql

# Name of the Askbot database.
# Django database argument `NAME`.
askbot_db_name: askdb

# Name of the database user for the Askbot database.
# Django database argument `USER`.
askbot_db_user: "{{ askbot_user }}"

# Password of the database user for the Askbot database.
# Django database argument `PASSWORD`.
askbot_db_pass: "VHw0e8hsodih2oh"

# Should not be changed.
askbot_db_delegate_to: "{{ askbot_db_host | replace('localhost', inventory_hostname) | replace('127.0.0.1', inventory_hostname) }}"

#
# Cache (memcached)
#

# Location of the memcached daemon; ip:port values, or unix socket path (without `unix:/`).
# Django cache argument `LOCATION`.
askbot_cache_location: '/run/memcached/memcached.sock'

# The default timeout to use for the cache (seconds).
# Django cache argument `TIMEOUT`.
askbot_cache_timeout: 3600

#
# E-mails
#

# Address of the SMTP server for sending e-mails.
# Django setting `EMAIL_HOST`.
askbot_smtp_host: "{{ smtp_host | default('localhost') }}"

# Port number of the SMTP server for sending e-mails.
# Django setting `EMAIL_PORT`.
askbot_smtp_port: "{{ smtp_port | default('25') }}"

# Whether the SMTP server uses TLS.
# Django setting `EMAIL_USE_TLS`.
askbot_smtp_tls_enabled: false

# The default 'from' address that e-mails from the Askbot will appear to come
# from (e.g. no-reply@example.org).
# Django setting `DEFAULT_FROM_EMAIL` and `SERVER_EMAIL`.
askbot_smtp_default_from: "{{ smtp_noreply | default('no-reply@example.org') }}"

# Subject-line prefix for email messages sent from Askbot.
# Django setting `EMAIL_SUBJECT_PREFIX`.
askbot_smtp_subject_prefix: '[Askbot] '

