---

- name: install virtualenv
  yum: name=python-virtualenv
  become_user: root
  become: yes
  become_method: sudo

- name: install system packages required for askbot dependencies
  yum: state=present name={{ item }}
  with_items:
    - gcc
    - git
    - libtiff-devel
    - libjpeg-devel 
    - zlib-devel
    - freetype-devel
    - lcms2-devel
    - libwebp-devel
    - tcl-devel
    - tk-devel
    - libraqm-devel
  become_user: root
  become: yes
  become_method: sudo
