- name: install askbot service systemd unit file
  template: src=askbot.service.j2 dest=/etc/systemd/system/askbot.service
  become_user: root
  become: yes
  become_method: sudo

- name: start askbot service
  systemd: state=started name=askbot daemon_reload=yes
  become_user: root
  become: yes
  become_method: sudo

- name: enable askbot.service
  systemd:
    name: askbot
    enabled: yes
  become_user: root
  become: yes
  become_method: sudo
